//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace CPTTProTest {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private SMS_Register_InfoDataTable tableSMS_Register_Info;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["SMS_Register_Info"] != null)) {
                    this.Tables.Add(new SMS_Register_InfoDataTable(ds.Tables["SMS_Register_Info"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SMS_Register_InfoDataTable SMS_Register_Info {
            get {
                return this.tableSMS_Register_Info;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["SMS_Register_Info"] != null)) {
                this.Tables.Add(new SMS_Register_InfoDataTable(ds.Tables["SMS_Register_Info"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableSMS_Register_Info = ((SMS_Register_InfoDataTable)(this.Tables["SMS_Register_Info"]));
            if ((this.tableSMS_Register_Info != null)) {
                this.tableSMS_Register_Info.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("zh-CN");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableSMS_Register_Info = new SMS_Register_InfoDataTable();
            this.Tables.Add(this.tableSMS_Register_Info);
        }
        
        private bool ShouldSerializeSMS_Register_Info() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void SMS_Register_InfoRowChangeEventHandler(object sender, SMS_Register_InfoRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SMS_Register_InfoDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnsmsInfo_id;
            
            private DataColumn columnstudInfo_stuid;
            
            private DataColumn columnfamilial_name;
            
            private DataColumn columnmobilePhone_number;
            
            private DataColumn columnstu_grade;
            
            private DataColumn columnstu_class;
            
            internal SMS_Register_InfoDataTable() : 
                    base("SMS_Register_Info") {
                this.InitClass();
            }
            
            internal SMS_Register_InfoDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn smsInfo_idColumn {
                get {
                    return this.columnsmsInfo_id;
                }
            }
            
            internal DataColumn studInfo_stuidColumn {
                get {
                    return this.columnstudInfo_stuid;
                }
            }
            
            internal DataColumn familial_nameColumn {
                get {
                    return this.columnfamilial_name;
                }
            }
            
            internal DataColumn mobilePhone_numberColumn {
                get {
                    return this.columnmobilePhone_number;
                }
            }
            
            internal DataColumn stu_gradeColumn {
                get {
                    return this.columnstu_grade;
                }
            }
            
            internal DataColumn stu_classColumn {
                get {
                    return this.columnstu_class;
                }
            }
            
            public SMS_Register_InfoRow this[int index] {
                get {
                    return ((SMS_Register_InfoRow)(this.Rows[index]));
                }
            }
            
            public event SMS_Register_InfoRowChangeEventHandler SMS_Register_InfoRowChanged;
            
            public event SMS_Register_InfoRowChangeEventHandler SMS_Register_InfoRowChanging;
            
            public event SMS_Register_InfoRowChangeEventHandler SMS_Register_InfoRowDeleted;
            
            public event SMS_Register_InfoRowChangeEventHandler SMS_Register_InfoRowDeleting;
            
            public void AddSMS_Register_InfoRow(SMS_Register_InfoRow row) {
                this.Rows.Add(row);
            }
            
            public SMS_Register_InfoRow AddSMS_Register_InfoRow(string studInfo_stuid, string familial_name, string mobilePhone_number, short stu_grade, short stu_class) {
                SMS_Register_InfoRow rowSMS_Register_InfoRow = ((SMS_Register_InfoRow)(this.NewRow()));
                rowSMS_Register_InfoRow.ItemArray = new object[] {
                        null,
                        studInfo_stuid,
                        familial_name,
                        mobilePhone_number,
                        stu_grade,
                        stu_class};
                this.Rows.Add(rowSMS_Register_InfoRow);
                return rowSMS_Register_InfoRow;
            }
            
            public SMS_Register_InfoRow FindBysmsInfo_id(int smsInfo_id) {
                return ((SMS_Register_InfoRow)(this.Rows.Find(new object[] {
                            smsInfo_id})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                SMS_Register_InfoDataTable cln = ((SMS_Register_InfoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new SMS_Register_InfoDataTable();
            }
            
            internal void InitVars() {
                this.columnsmsInfo_id = this.Columns["smsInfo_id"];
                this.columnstudInfo_stuid = this.Columns["studInfo_stuid"];
                this.columnfamilial_name = this.Columns["familial_name"];
                this.columnmobilePhone_number = this.Columns["mobilePhone_number"];
                this.columnstu_grade = this.Columns["stu_grade"];
                this.columnstu_class = this.Columns["stu_class"];
            }
            
            private void InitClass() {
                this.columnsmsInfo_id = new DataColumn("smsInfo_id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnsmsInfo_id);
                this.columnstudInfo_stuid = new DataColumn("studInfo_stuid", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstudInfo_stuid);
                this.columnfamilial_name = new DataColumn("familial_name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnfamilial_name);
                this.columnmobilePhone_number = new DataColumn("mobilePhone_number", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmobilePhone_number);
                this.columnstu_grade = new DataColumn("stu_grade", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstu_grade);
                this.columnstu_class = new DataColumn("stu_class", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstu_class);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnsmsInfo_id}, true));
                this.columnsmsInfo_id.AutoIncrement = true;
                this.columnsmsInfo_id.AllowDBNull = false;
                this.columnsmsInfo_id.ReadOnly = true;
                this.columnsmsInfo_id.Unique = true;
                this.columnstudInfo_stuid.AllowDBNull = false;
                this.columnfamilial_name.AllowDBNull = false;
                this.columnmobilePhone_number.AllowDBNull = false;
                this.columnstu_grade.AllowDBNull = false;
                this.columnstu_class.AllowDBNull = false;
            }
            
            public SMS_Register_InfoRow NewSMS_Register_InfoRow() {
                return ((SMS_Register_InfoRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new SMS_Register_InfoRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(SMS_Register_InfoRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SMS_Register_InfoRowChanged != null)) {
                    this.SMS_Register_InfoRowChanged(this, new SMS_Register_InfoRowChangeEvent(((SMS_Register_InfoRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SMS_Register_InfoRowChanging != null)) {
                    this.SMS_Register_InfoRowChanging(this, new SMS_Register_InfoRowChangeEvent(((SMS_Register_InfoRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SMS_Register_InfoRowDeleted != null)) {
                    this.SMS_Register_InfoRowDeleted(this, new SMS_Register_InfoRowChangeEvent(((SMS_Register_InfoRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SMS_Register_InfoRowDeleting != null)) {
                    this.SMS_Register_InfoRowDeleting(this, new SMS_Register_InfoRowChangeEvent(((SMS_Register_InfoRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveSMS_Register_InfoRow(SMS_Register_InfoRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SMS_Register_InfoRow : DataRow {
            
            private SMS_Register_InfoDataTable tableSMS_Register_Info;
            
            internal SMS_Register_InfoRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableSMS_Register_Info = ((SMS_Register_InfoDataTable)(this.Table));
            }
            
            public int smsInfo_id {
                get {
                    return ((int)(this[this.tableSMS_Register_Info.smsInfo_idColumn]));
                }
                set {
                    this[this.tableSMS_Register_Info.smsInfo_idColumn] = value;
                }
            }
            
            public string studInfo_stuid {
                get {
                    return ((string)(this[this.tableSMS_Register_Info.studInfo_stuidColumn]));
                }
                set {
                    this[this.tableSMS_Register_Info.studInfo_stuidColumn] = value;
                }
            }
            
            public string familial_name {
                get {
                    return ((string)(this[this.tableSMS_Register_Info.familial_nameColumn]));
                }
                set {
                    this[this.tableSMS_Register_Info.familial_nameColumn] = value;
                }
            }
            
            public string mobilePhone_number {
                get {
                    return ((string)(this[this.tableSMS_Register_Info.mobilePhone_numberColumn]));
                }
                set {
                    this[this.tableSMS_Register_Info.mobilePhone_numberColumn] = value;
                }
            }
            
            public short stu_grade {
                get {
                    return ((short)(this[this.tableSMS_Register_Info.stu_gradeColumn]));
                }
                set {
                    this[this.tableSMS_Register_Info.stu_gradeColumn] = value;
                }
            }
            
            public short stu_class {
                get {
                    return ((short)(this[this.tableSMS_Register_Info.stu_classColumn]));
                }
                set {
                    this[this.tableSMS_Register_Info.stu_classColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SMS_Register_InfoRowChangeEvent : EventArgs {
            
            private SMS_Register_InfoRow eventRow;
            
            private DataRowAction eventAction;
            
            public SMS_Register_InfoRowChangeEvent(SMS_Register_InfoRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public SMS_Register_InfoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
